server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mimall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 118.31.16.35
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  redis:
    host: 118.31.16.35
    port: 6379
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true